### ISSUE TITLE
Where are unminimized sources?

### ISSUE THREAD

**Issue by jirutka** [HubPress/hubpress.io#10]
This repo contains only bloated `app.js` file (size 5 MiB) that mixes hubpress code with many third-party libs.

**Comment by anthonny** [comment]
Yes, i need to make some refactor before i publish all sources.

Actually i want to test the project and see if users adopt the product.
I intend to give source files at the end of the month. If i can i'll do ti earlier.
Is it annoying for you?

**Comment by matthewp** [comment]
Not so much annoying as open-source is good and you can get contributors. For example I'd like to customize the url structure because the current one is incompatible with my existing blog (which I would like to migrate to this while keeping my urls).  So I'd be happy to contribute to the project and add this feature, but can't currently.

**Comment by rogeriopvl** [comment]
+1

**Comment by anthonny** [comment]
Development branch is available.
I thought of taking time to make tests and documentation, but i was really important for me that you have sources as soon as possible.

So... There isn't unit test and a first part of the doc will come soon. I'll do my best.

**Comment by anthonny** [comment]
Development branch is available.
I thought of taking time to make tests and documentation, but i was really important for me that you have sources as soon as possible.

So... There isn't unit test and a first part of the doc will come soon. I'll do my best.
