### ISSUE TITLE
script 404 Not Found

### ISSUE THREAD

**Issue by oussemos** [HubPress/hubpress.io#110]
Hello,

There is any other configs to do to make it work ? I have somes scripts not found Like

http://oussema.cherni.tn/hubpress.io/hubpress/scripts/Dexie.min.js.map
http://oussema.cherni.tn/__opal_source_maps__/opal.js.map

And are pointing always to my home page

**Comment by anthonny** [comment]
Hi @oussemos !

You already use your **oussemos.github.io** you must work on the branch **gh-pages** : 
1. In the settings of your repository, set the branch **gh-pages** as default branch
2. Update your **config.json** on the branch **gh-pages**
3. Login HubPress at http://oussema.cherni.tn/hubpress.io/hubpress/

Map files are not available, that's why you have a 404 but that does not prevent HubPress from working

**Comment by AndreaPravato** [comment]
I stumbled upon a similar issue. I am not using custom domain; I am using master branch of andreapravato.github.io, and when I try to save a post there are errors related to: http://andreapravato.github.io/hubpress/scripts/Dexie.min.js.map not found

**Comment by anthonny** [comment]
I close the issue, feel free to reopen if necessary
