### ISSUE TITLE
Dévellopement en local

### ISSUE THREAD

**Issue by FelixINX** [HubPress/hubpress.io#190]
Bonjour,

J'ai trouvé que le dévellopement en local à l'aide de la commande `jekyll serve` ne marche pas au complet.
Seul l'administration ne marche pas (`/hubpress`), et retroune des erreurs de 404. Le tout vient du fait que;
1. L'ordinateur essaye de rechercher les ressources en ligne et non en local (ce qui est bien!)
2. Mon repo est privée, alors il ne peut pas aller cherche les infos/fichiers.

Merci

**Comment by felixinx** [comment]
J'ai aussi trouvé une autre erreur qui pourrait être très dangeureuse. N'importe qui peut se connecter à l'administration. Selon mes test, on ne peut pas modifié (erreur dans la console), mais c'est quand même dangeureux. Est-ce-qu'il y aurait un moyen de limiter l'authentification à l'adresse email du compte/repo ?

**Comment by anthonny** [comment]
Bonjour @felixinx!

You can't use `jekyll serve` because HubPress do not work with Jekyll :)

For the adminsitration, it is not an error. Your Github repository is public and everybody can read the content of its. HubPress use the GitHub rights, so you can't save/publish if you don't have the right.

In read-only, HubPress is just an other representation of the content, no more.

Qu'en penses-tu ?

**Comment by felixinx** [comment]
Bon je ne sais plus quelle langue utilisé... Franglais?

I was sure that the Github Pages server uses `jekyll serve` for the starting. I will try with `npm start`?

I agree with the Read-Only mode, but maybe block the login to email adress, will be more nice for end user (admin/moderator of the blog)?

Sinon, merci pour ta réponse!

**Comment by jaredmorgs** [comment]
Merci pour le rapport de bogue. Est-ce OK pour fermer la question, compte tenu de son âge?

**Comment by FelixINX** [comment]
Oui!
