### ISSUE TITLE
Asciidoc Style issues

### ISSUE THREAD

**Issue by KurtStam** [HubPress/hubpress.io#193]
Hi guys,

First of all - great work!  Love it!

I'm using the ichi style and I'm missing some asciidoc style for instance the WARNING: (Orange triangle)  and NOTE: (Blue I) show up perfectly fine in the viewer, but are not shown at all in the final posted page.
I can fix it by adding a reference to the hubpress/styles/main.css:
https://github.com/KurtStam/kurtstam.github.io/commit/54c60d48658743c0f3182f256f0524685bb86bcd#diff-b3b8f7e8eb3a72ab0f3e81b4f8ac0ae5
However this then messes with the layout.

Hopefully this is an easy fix for you guys!

Cheers,

--Kurt

**Comment by lametaweb** [comment]
Hi everyone,

I`ve just started with HubPress and I´m enjoying very much so far! Great work, I agree.
I solved this issue by adding two lines to the default.hbs file:
https://github.com/lametaweb/lametaweb.github.io/commit/0660d7d0780fa4c092d233cf830b30ae2413d7d8
Hope it helps!

**Comment by jaredmorgs** [comment]
I had the same problem when I was using the jekyll-asciidoc-quickstart from
Asciidoctor.

I had to add the font-awesome styles in so the admonition icons would
publish in my user guide. I think the default foundation style set that
asciidoctor.js uses doesn't include the files by default.

Would you be able to create a patch for just those two lines of code on
/development and we can merge that in for the next release.

Thanks for spending the time on figuring out what was happening there. This
will be a great help for many HubPress users.

**Comment by lametaweb** [comment]
Hi @jaredmorgs I´ve just created a pull request for this issue. I hope it´s all OK. Cheers.

**Comment by KurtStam** [comment]
Hi @lametaweb , thanks for looking into this. I just tried out the fix and maybe I'm missing something but it still does not seem to work for me.

The asciidoc on my test page is:
= Test
:hp-tags: OpenShift, Fabric8, OSX
:numbered:

NOTE: testing

Which in the preview looks like this: https://www.dropbox.com/s/u5qllslt58sxb95/Screenshot%202015-04-29%2013.26.06.png?dl=0

However the final page looks like
https://www.dropbox.com/s/9j3qu786mv3ewg1/Screenshot%202015-04-29%2013.29.21.png?dl=0
see also:
https://kurtstam.github.io/2015/04/29/Test.html

Where the NOTE renders like a box without the icon.

--Kurt

**Comment by KurtStam** [comment]
Turns out my browser was blocking mixed active content. After I updated your second like to relative link to be relative things started working

     <link rel="stylesheet" type="text/css" href="hubpress/styles/asciidoctor.css" />

Cheers,

--Kurt

**Comment by lametaweb** [comment]
Hi @KurtStam , I've just gone to https://kurtstam.github.io/2015/04/29/Test.html, and I can't see the asciidoc icon rendered. Did you finally get it solved?

Cheers

**Comment by KurtStam** [comment]
It depends on the browser you use I later found out. Safari works, 
Firefox and Chrome do not.

--Kurt

**Comment by lametaweb** [comment]
No, my fault, it's a cross-domain security problem. You should use this line with your blog:
\<link rel="stylesheet" type="text/css" href="https://kurtstam.github.io/hubpress/styles/asciidoctor.css">
And I'll add asap these changes to [my PR](https://github.com/HubPress/hubpress.io/pull/198):
* add /src/themes/ichi/assets/css/asciidoctor.css file
* edit second html link label so that now it would be: \<link rel="stylesheet" type="text/css" href="{{asset "css/asciidoctor.css"}}" />

I apologize. 
Cheers.

**Comment by lametaweb** [comment]
PR updated. Cheers.

**Comment by raisedadead** [comment]
Hi @lametaweb 

This issue is reproducible for Casper, Roon  #220 , etc. I strongly feel if the change is going to be for all themes ( at least currently within hubpress package ), shouldn't this fix go at more parent level?

As @jaredmorgs said maybe @anthonny can clarify better. 
But please let me know your thoughts, would like to see how it goes...

thanks,
raisedadead

**Comment by lametaweb** [comment]
Hi @raisedadead, in this project I'm another forker, like you. I only researched a little about this problem and cretaed a Pull Request in order to show a possible solution rather than create the definitive fix. So until the solution comes (I know like you about it) choose a theme and then modify the files in your repository.

Best regards.

**Comment by anthonny** [comment]
Hi everybody,

I apologize for not having answered earlier, really sorry.

In the preview, i use a stylesheet that i have built with the asciidoctor-stylesheet-factory.
I do not use this stylesheet in themes because i do not want to modify them. 
The reason is simple, themes are the same that the Ghost theme and today, it's easy to add a new Ghost theme.
If i add the asciidoctor as a requirement for a theme, every Ghost theme must be modified.

**Comment by Ardemius** [comment]
Hi,

I do confirm the fix is also working for me (Roon theme), as long as the `asciidoctor.css` is effectively referenced from **your** GitHub repo:

    <link rel="stylesheet" type="text/css" href="https://<your_name>.github.io/hubpress/styles/asciidoctor.css">

However, with it I now have the admonition icons in italics ???
This seems to come from the `themes/Roon/assets/css/screen.css`:

    article .text em, article .text i {
        font-style: italic;
    }

Which is not the case in the viewer.

Cheers,
Thomas

**Comment by jaredmorgs** [comment]
Based on @anthonny's comment above, this issue isn't a candidate for action from HubPress's end.
