### ISSUE TITLE
General questions about using hubpress for a developer blog

### ISSUE THREAD

**Issue by simonhf** [HubPress/hubpress.io#199]
What are good examples of github io developer blogs created with hubpress?

What are good examples of syntax highlighting code blocks?

Is there a way to fold / unfold larger blocks of code, e.g. show only the first n lines of a 500 line code snippet?

Is there a way for readers to subscribe to a hubpress based blog running on github io? With RSS?

Are there any tools to create / render on the fly simple diagrams and/or graphs / bar charts via ascii markup instead of messing around with actual images, i.e. complete blog article in one text file, rather than text file + image file(s)? For example, something like [1] or [2] fed by markdown text?

Thanks.

[1] http://jtblin.github.io/angular-chart.js/
[2] http://knsv.github.io/mermaid/

**Comment by jaredmorgs** [comment]
All good topics for the Users Guide.

I'm not a developer, but I write plenty of detailed blog posts with code
samples embedded: http://jaredmorgs.github.io

Take a look at the blog post on Javadocs I wrote: it has plenty of embedded
samples and you can view them in the blog source to see how they were
written. You can also check the Asciidoctor Users Guide for some great
examples of how to use code syntax blocks.

On wrapping code samples, I couldn't find anything obvious in the
Asciidoctor docs, but I know that in the Asciidoctor Users Guide they have
show/hide blocks. I've put a tweet out to the Asciidoctor team to see if
they can help us with that.

RSS support depends on whether @anthonny has implemented RSS in the themes.
I believe at one point he had to turn them off because they were broken.

There are ways of making text based diagrams which are transformed when
published by Asciidoctor. See
http://asciidoctor.org/docs/asciidoctor-diagram. These use PlantUML,
Graphviz, ditaa, or Shaape syntax.

Anthonny would need to add the extensions into HubPress for them to work.

**Comment by ciekawy** [comment]
+1 
I wonder mow to configure mermaid

**Comment by jaredmorgs** [comment]
Just doing a bit of issue maintenance (as you can see, it's well overdue on this repo 😞).

This was a general question, so I'm closing it off for now.
