### ISSUE TITLE
Inconsistencies between browser instances

### ISSUE THREAD

**Issue by konstantinklein** [HubPress/hubpress.io#211]
First of all: great idea, great project, apparently a great community.

Now: I'm having problems running a HubPress blog from more than one machine. An entry written on computer B, in Firefox, doesn't appear in the list of entries on computer A, in Google Chrome. It still is there in the repository and in the local clone on computer A. But when regenerating the pages from computer A, the entry disappears from the main index.html.

Emptying the cache on computer A doesn't help. Is there a way to sync a local browser instance of HubPress with the current HubPress fork in my GitHub account?

**Comment by anthonny** [comment]
Hi @konstantinklein !

Thank you for trying HubPress :smile: 

Actually, the only way to sync posts is to logout/login from HubPress.
I will add a button to sync your posts in a future version

**Comment by konstantinklein** [comment]
Hi @anthonny ,

that's what I've tried before, and did again after reading your message. The bad news is: it doesn't work. Upon login I receive a message that all entries have been synced. A look into my GitHub repository, however, reveils that there are .adocs which I've written earlier with HubPress, which are not syncronized by the currently running instance of HubPress. In return, HubPress doesn't include them in the main index.html even when the appropriate HTML files are still accessible from a browser.

The page in question is http://blog.konstantinklein.com/2015/05/11/Lava-pffft.html, the _docs/2015-05-11-Lava-pffft.adoc is there as well, but HubPress won't recognize any of them. And I haven't edited any of them manually, i.e. locally and pushed them to GitHub afterwards.

Any ideas? Thanks a lot!

**Comment by raisedadead** [comment]
Hi @konstantinklein ,

I figured out the issue, its because the IndexedDB on chrome is a bit tricky to delete via the usual methods. 

So just a work around :
1. Logout from hubpress, and close the tab ( just for safety, shouldn't matter if you don't ).
2. In a separate tab on chrome's address bar go to: chrome://settings/cookies
3. In the search box on the dialog, type your domain name, such as : yourusername.github.io, this is where your blog is hosted, it should be your custom domain in case you are using one.
4. Finally click the cross button ( 'X' ) to remove the cookies, IndexedDB, etc., relative to entries for your domain.

Then simply refresh and re-login to hubpress. Should do the job. While personally I think maybe a button as suggested by @anthonny should be a more viable option for the everyday user.

Refer below for details:
http://stackoverflow.com/questions/9384128/how-to-delete-indexeddb-in-chrome

Thanks.

regards,
raisedadead

**Comment by konstantinklein** [comment]
Hi @raisedadead,

in a separate conversation on Gitter, @anthonny already talked me through the deletion of the IndexedDB in Chrome, which was particularly useful since deleting everything (cookies and anything elese) related to HubPress in Chrome's settings hadn't helped before.

Doing the same thing in Firefox (Windows) worked like a charm, though.

Thanks!

konstantin

**Comment by jaredmorgs** [comment]
I reckon we should add this great suggestion to the README/User Guide. I
also think that generic message I grammar checked "Check developer console
for details" needs to show folks how to actually get there. It displays
pretty regularly. I think because of the terseness of that message, a link
to the user guide might be worthwhile.

**Comment by raisedadead** [comment]
@konstantinklein and @jaredmorgs  I agree this should go into the user guide as a F.A.Q at least :+1: 

thanks,
raisedadead

**Comment by mubix** [comment]
I'm having the same issues, it would be nice to have just a general "sync" button

**Comment by jaredmorgs** [comment]
We've now got the resync function which fixes this issue.
