### ISSUE TITLE
Use private repository for organization / access control

### ISSUE THREAD

**Issue by abhayghatpande** [HubPress/hubpress.io#266]
Hi, I am new to GitHub so this might be a silly question, but I'm not clear how we could control who can clone the repository and who can publish posts to it.

I forked the hubpress.io repository to our organization and followed all the steps mentioned in the Readme to setup the blog. It works great.

My questions:
(1) Who can clone the repository? Will all the contents of the posts be accessible / readable by those who clone?
(2) Can I make the repository private?
(3) How to control access to who can create posts? Right now anyone can logon to the admin console.

Thank you for all your efforts.

**Comment by abhayghatpande** [comment]
I could make the repo private by duplicating it, but then will I be able to update it to the latest HubPress goodness?

**Comment by anthonny** [comment]
Hi @abhayghatpande !
Thank you for trying HubPress :+1: 

(1) Everyone can clone a public repository, with all the content. However they can only modify their fork, not your repository.
(2) I suppose that HubPress work on a private repository but you need to upgrade your account
(3) Everyone can login in your fork of hubpress, it's logical because your repository is public and everyone can read the content. But only the authorized people can make some changes.

For your last question, there is a limit on github: you can only have one fork of a repository by account. If you want to have more than one copy of hubpress, you need to upgrade them manually through git commands

**Comment by abhayghatpande** [comment]
Hi @anthonny 

Thanks for the reply. I am beginning to understand how this works.
So how can I control who can do what? For example, only the admin should be able to change the logo, theme, etc., while other team members should be able to write / publish content.
I don't suppose there is a way to implement a workflow, where content can be submitted by the author, then curated/edited and published by the admin?

**Comment by jaredmorgs** [comment]
Granularity within HubPress isn't supported. There is no concept of Admin vs User. HubPress is designed to be used by a single blogger primarily. There is a concept of post ownership now in 0.6.x, which is outlined here: https://hubpress.gitbooks.io/hubpress-knowledgebase/content/write/multiple_authors.html
