### ISSUE TITLE
Better Redirect URL handling and Non-Breaking Space support in URLs

### ISSUE THREAD

**Issue by pysaumont** [HubPress/hubpress.io#285]
Hello,

I am trying to create my first post and I get this error. Here is the content of the post:

== My Title

My first post.

Thanks

**Comment by jaredmorgs** [comment]
You need to start your blog title with a Heading 1.

= My Title

My First Post

See https://github.com/HubPress/hubpress.io/blob/development/docs/README.adoc#blog-title-and-headings for more information about how to construct a blog post in HubPress.

Also check https://github.com/HubPress/hubpress.io/blob/development/docs/README.adoc#62-hubpress-parameters for a list of parameters you can use to customise each blog post with cover art, publish date, and tags.

**Comment by pysaumont** [comment]
Thanks for you answer. However, I made the error in my question, not in the blog post. I typed:

= My Title

My first post.

By the way, I get the same error when I try to change the settings.

Could this be related to redirection? I am asking this because I first was able to set some settings (blog title an description) and this is no longer working since I installed a redirection. I tried to remove the redirection, but it does not work neither. 

Also, I fork Hubpress in a private github account. Could this be the reason for the problem?

**Comment by cliftonc** [comment]
Also getting this, makes it unusable.

**Comment by fpinjava** [comment]
@cliftonc 
I removed the redirection and manage to make it almost work by creating empty articles in the interface, which creates the necessary files in the github projet. Then I pull the changes locally, update the new articles and push the modifications. Then I make all necessary edits using the same procedure. When the articles are ok, I pull once more, make the necessary changes to the HTML generated files (since I did not find how to obtain things like non breaking spaces in titles and the like).

This is quite unstable, since the modifications to the HTML generated files will be lost if I modify the ascciidoc files, but its better than nothing. I don't care so much about not being able to modify the articles in the web interface, even if it would be much better to be able to do both (edit in the interface or locally)

I eventually put back the redirection but I can't say what exact configuration is used because it can only be done in my provider's interface, and it offers only three options to chose from: "Direct permanent", "Direct temporary" and "Transparent". I chose "Direct permanent" which seems to be working, but the original url appears in the url bar, not the redirected one. I have not configured the url in the HubPress configuration interface, so maybe it is what must be done to get the redirected url in the url bar, but I am reluctant to try this because I am afraid to break it all.

I hope these informations can help. HubPress fits my requirements perfectly, so I would really like to find a reliable way to use it!

**Comment by anthonny** [comment]
Hubpress do not work well on private repository that's why you have problems. I'll try to fix that's in the nextversion

**Comment by fpinjava** [comment]
@anthonny 
I forgot to say that I have switched to a public repository. I probably should test again using the web interface, but I am reluctant to do it because I am afraid to break something. Beside the ability to edit posts from anywhere when not having git access (since I don't use the web interface), I am still missing two features: 1) having the redirected url showing in the url bar instead of the github url, and 2) more control over the generated HTML, such as non breaking spaces in titles (including the post title). I tried all possibilities I could think of, but without success. The only solution I found was to edit the generated HTML files manually.

HubPress is however the best blog solution I have found until now!

**Comment by jaredmorgs** [comment]
The good news is that editing posts in GitHub and then syncing over to HubPress is much better in 0.7.0. 

The resync posts function works much better between browsers now as well.

The other issue with redirects are still outstanding. Would you still find this feature valuable if we fixed them, or have you resolved the issue by switching providers (if I understand the issue correctly)?

**Comment by jaredmorgs** [comment]
Please reopen if the issue persists or join hubpressio.slack.com to talk through the idea further so we can update the scope of this issue.
