### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by chsm** [HubPress/hubpress.io#371]
Why doesn't HubPress support Markdown or other popular lightweight markups?

**Comment by jaredmorgs** [comment]
Practically all static site Jekyll blogging platforms support one of the 26
different flavors of markdown.

HubPress sets itself apart because it supports the AsciiDoc syntax only. It
is more suitable for bloggers who want to write more detailed blogs with
complex syntax.

On Sat, 16 Apr 2016, 02:40 Chase May <notifications@github.com> wrote:

> Why doesn't HubPress support Markdown or other popular lightweight markups?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/371>
>
-- 

Sent from Mobile.

**Comment by kfkelvinng** [comment]
Does the comment in #25 meant hubpress which use asciidoctor as backend would support a subset of markdown?

**Comment by jaredmorgs** [comment]
It has limited legacy support for some markdown constructs.

They are only supported to help folks migrate from markdown to AsciiDoc,
not really as a long term solution.

On Fri, 22 Apr 2016, 00:03 kfkelvinng <notifications@github.com> wrote:

> Does the comment in #25
> <https://github.com/HubPress/hubpress.io/issues/25> meant hubpress which
> use asciidoctor as backend would support a subset of markdown?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/371#issuecomment-212934497>
>
-- 

Sent from Mobile.
