### ISSUE TITLE
Hubpress doesn't retain original author

### ISSUE THREAD

**Issue by dashorst** [HubPress/hubpress.io#394]
At our company blog we sometimes fix issues in posts that were written by another author. This means a commit happens in another author's name. Hubpress incorrectly gives the last committer authorship of the post.

Case in point:

https://github.com/topicusonderwijs/topicusonderwijs.github.io/blob/master/_posts/2016-05-23-Models-are-pointers.adoc

was written by sanderevers and subsequently edited by me (merely added a publication date) a month later. But now the post is displaying me (dashorst) as the author of the article:

https://topicusonderwijs.github.io/2016/05/23/Models-are-pointers.html

This is with Hubpress 0.5.1 (to which I just upgraded).

Things I've tried:
- Press save in the admin panel
- Press save again in the admin panel

**Comment by anthonny** [comment]
Hi @dashorst 

It's really cool to see that your company use HubPress! I'm so happy with that you made my day.

The problem is that your master is not in the version 0.5.1 https://github.com/topicusonderwijs/topicusonderwijs.github.io/blob/master/hubpress/index.html#L46

Your pull request https://github.com/topicusonderwijs/topicusonderwijs.github.io/pull/1 has be done on the branch `gh-pages`

**Comment by dashorst** [comment]
Ah. yes... thanks for noticing and the quick response!
