### ISSUE TITLE
Question: what's the future of this project/roadmap?

### ISSUE THREAD

**Issue by rdwatters** [HubPress/hubpress.io#447]
I just barely discovered this project through staticgen. It's a really cool concept, but it looks like there haven't been any commits or updates in months. Roadmap or plans?

**Comment by anthonny** [comment]
Hi @rdwatters 

We are working with @jaredmorgs on the roadmap of the project. The project is not dead but i can't work as much as i want.

Here the project of the next version (0.7.0) https://github.com/HubPress/hubpress.io/projects/1

**Comment by laposheureux** [comment]
Is there any plan to bundle changes into single commits? I've written and made edits to two posts so far (along with various config changes) and the repository now has 600+ commits. It appears every single file change is made as a unique commit instead of a batch of changes into a single commit (or a small number of commits).

**Comment by jaredmorgs** [comment]
@laposheureux I think you'll find the way commits are batched in 0.7.0 to be much more efficient. 

On my 90 post blog it used to take 4 minutes to rebuild the site after publishing. It now takes 40 seconds!
