### ISSUE TITLE
Login with 2FA prompts for the 2FA key twice every time.

### ISSUE THREAD

**Issue by laposheureux** [HubPress/hubpress.io#456]
I find that I have to:

1. Attempt to authenticate without 2FA
2. Be prompted for a 2FA key
3. Input the key, try to auth
4. Be prompted for a 2FA key again
5. Wait for the key to expire (30s)
6. Enter the next key to to successfully authenticate

This happens on every single login in multiple browsers.

**Comment by furcon** [comment]
ditto. I've the same problem.

**Comment by davidthewatson** [comment]
Me too.

**Comment by jaredmorgs** [comment]
@anthonny I seem to remember that the 2FA issues were fixed by work done with new GitHub APIs in 0.7.0

@laposheureux @jarbro @davidthewatson @furcon could you do us a favour and upgrade to 0.7.0 through your HubPress admin. Or if 2FA is preventing you from doing so, create a PR against upstream and pull down the latest changes into your HubPress instances.

Thanks for your help with diagnosis.

**Comment by anthonny** [comment]
@jaredmorgs yes the 2FA is fixed with the 0.7.0 and everything should be ok.

**Comment by laposheureux** [comment]
Can confirm that I no longer see the double-prompt for 2FA.
